# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPlatformUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=40, null=True)),
                ('avatar', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.CharField(blank=True, max_length=20, null=True)),
                ('openid', models.CharField(blank=True, max_length=200, null=True)),
                ('unionid', models.CharField(blank=True, max_length=200, null=True)),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('expiretime', models.DateTimeField(blank=True, null=True)),
                ('profileurl', models.CharField(blank=True, max_length=200, null=True)),
                ('ts', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'auth_platform_user',
            },
        ),
    ]
