# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170328_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forder',
            old_name='relateobj',
            new_name='relate_obj',
        ),
        migrations.RemoveField(
            model_name='forder',
            name='transfer',
        ),
        migrations.AddField(
            model_name='forder',
            name='relate_id',
            field=models.IntegerField(null=True, verbose_name='关联交易'),
        ),
    ]
