# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAccountTransferAudits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfertype', models.CharField(choices=[('inpour', '充值'), ('withdraw', '提现')], max_length=20, null=True, verbose_name='交易类型')),
                ('certificate', models.CharField(blank=True, max_length=200, null=True, verbose_name='充值凭证')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='金额')),
                ('transfer_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='收款账户')),
                ('status', models.IntegerField(choices=[(0, '审核不通过'), (1, '审核通过'), (2, '待审核')], null=True, verbose_name='审核状态')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('audit_time', models.DateTimeField(null=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '充值&提现',
                'verbose_name_plural': '充值&提现列表',
                'db_table': 'f_account_transfer_audits',
            },
        ),
        migrations.CreateModel(
            name='FOrder',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='订单号')),
                ('relate_obj', models.CharField(blank=True, max_length=20, null=True, verbose_name='关联对象')),
                ('relate_id', models.IntegerField(null=True, verbose_name='关联交易')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='总金额(元)')),
                ('paytype', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付方式')),
                ('transaction_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='第三方交易号')),
                ('orderstatus', models.IntegerField(blank=True, choices=[(0, '未支付'), (1, '已支付'), (2, '已退款'), (3, '交易成功'), (4, '交易关闭')], null=True, verbose_name='订单状态')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='下单时间')),
                ('paytime', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'f_orders',
            },
        ),
        migrations.CreateModel(
            name='FWalletBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('billtype', models.CharField(blank=True, max_length=20, null=True, verbose_name='账单类型')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='账单金额(元)')),
                ('paytype', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付方式')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='账号余额')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FOrder', verbose_name='订单')),
            ],
            options={
                'db_table': 'f_walletbills',
            },
        ),
    ]
