# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(null=True, verbose_name='商家id')),
                ('task_id', models.IntegerField(null=True, verbose_name='任务id')),
                ('customer_id', models.IntegerField(null=True, verbose_name='会员id')),
                ('wechat', models.CharField(blank=True, max_length=50, null=True, verbose_name='会员微信')),
                ('orderno', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名称')),
                ('certificate', models.CharField(blank=True, max_length=200, null=True, verbose_name='好评凭证')),
                ('status', models.IntegerField(null=True, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'cashbacks',
            },
        ),
        migrations.CreateModel(
            name='CashbackTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(null=True, verbose_name='商家id')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名称')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='返现金额')),
                ('max_count', models.IntegerField(null=True, verbose_name='最大参与人数')),
                ('expiretime', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'cashback_tasks',
            },
        ),
        migrations.CreateModel(
            name='CashbackTaskGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(null=True, verbose_name='商家id')),
                ('task_id', models.IntegerField(null=True, verbose_name='任务id')),
                ('shop_id', models.CharField(max_length=32, null=True, verbose_name='店铺id')),
                ('good_id', models.CharField(max_length=32, null=True, verbose_name='商品id')),
            ],
            options={
                'db_table': 'cashback_task_goods',
            },
        ),
    ]
