# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbacktaskgoods',
            old_name='good_id',
            new_name='goods_id',
        ),
    ]
