# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0002_auto_20170328_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashback',
            old_name='wechat',
            new_name='wxname',
        ),
        migrations.RemoveField(
            model_name='cashback',
            name='name',
        ),
    ]
