# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0003_auto_20170328_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashback',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='返现金额'),
        ),
    ]
