# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0004_cashback_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendsms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='商家id')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('content', models.CharField(blank=True, max_length=200, null=True, verbose_name='内容')),
                ('captcha', models.CharField(blank=True, max_length=100, null=True, verbose_name='验证码')),
                ('is_success', models.NullBooleanField(verbose_name='发送是否成功')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'sendsms',
            },
        ),
        migrations.CreateModel(
            name='WXOfficialConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='商家id')),
                ('appid', models.CharField(blank=True, max_length=200, null=True)),
                ('appsecret', models.CharField(blank=True, max_length=200, null=True)),
                ('mchid', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.CharField(max_length=200, null=True)),
                ('apptoken', models.CharField(max_length=200, null=True)),
                ('encodingaeskey', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'wxofficial_config',
            },
        ),
    ]
