# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0005_sendsms_wxofficialconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='status',
            field=models.IntegerField(choices=[(1, '申请中'), (2, '已完成'), (3, '已关闭')], null=True, verbose_name='状态'),
        ),
    ]
