# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashback', '0009_auto_20170402_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashback',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='cashback',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商家'),
        ),
    ]
