# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0010_auto_20170402_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashback',
            options={'verbose_name': '返现', 'verbose_name_plural': '返现列表'},
        ),
        migrations.AlterField(
            model_name='cashback',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
