# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0011_auto_20170402_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='status',
            field=models.IntegerField(choices=[(1, '待审核'), (2, '审核通过，等待平台打款'), (3, '关闭申请'), (4, '已完成')], null=True, verbose_name='状态'),
        ),
    ]
