# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0012_auto_20170402_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashback',
            name='showpic1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='买家秀'),
        ),
        migrations.AddField(
            model_name='cashback',
            name='showpic2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='买家秀'),
        ),
    ]
