# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='task_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='任务领取时间'),
        ),
    ]
