# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20170328_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='platid',
            new_name='pgoods_id',
        ),
    ]
