# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20170328_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='id',
            field=models.CharField(default='ad0e4018eeca48058c3ff338e683e398', max_length=32, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.CharField(default='7cce4e70e38b4a088c2ea770b2ba6c62', max_length=32, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
