# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20170328_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='platform',
            field=models.CharField(max_length=50, null=True, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商家'),
        ),
    ]
