# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20170408_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='user',
            new_name='seller',
        ),
    ]
