# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20170408_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='seller',
        ),
    ]
